import os
import sys
from PIL import Image, ImageDraw, ImageFont

font_path = "/usr/share/fonts/truetype/noto/NotoSans-Regular.ttf"
if not os.path.exists(font_path):
    print("Error: Font not found at", font_path)
    sys.exit(1)

# List of characters
chars = [chr(c) for c in range(32, 127)]
vn_lower = "àáảãạăằắẳẵặâầấẩẫậèéẻẽẹêềếểễệìíỉĩịòóỏõọôồốổỗộơờớởỡợùúủũụưừứửữựỳýỷỹỵđ"
vn_upper = "ÀÁẢÃẠĂẰẮẲẴẶÂẦẤẨẪẬÈÉẺẼẸÊỀẾỂỄỆÌÍỈĨỊÒÓỎÕỌÔỒỐỔỖỘƠỜỚỞỠỢÙÚỦŨỤƯỪỨỬỮỰỲÝỶỸỴĐ"
symbols = "★⚡⚔🛡♥✓✕→←↑↓•·«»"

all_chars = sorted(list(set(chars + list(vn_lower) + list(vn_upper) + list(symbols))))
print(f"Total glyphs to pack: {len(all_chars)}")

# Atlas configuration
ATLAS_W = 512
ATLAS_H = 512
FONT_SIZE = 26
PADDING = 4

font = ImageFont.truetype(font_path, FONT_SIZE)

atlas_img = Image.new("RGBA", (ATLAS_W, ATLAS_H), (0, 0, 0, 0))
draw = ImageDraw.Draw(atlas_img)

cur_x = PADDING
cur_y = PADDING
max_row_h = 0

glyph_entries = []

for ch in all_chars:
    cp = ord(ch)
    bbox = font.getbbox(ch)  # (left, top, right, bottom)
    if bbox is None or bbox[2] <= bbox[0] or bbox[3] <= bbox[1]:
        # Empty glyph like space
        advance = font.getlength(ch)
        glyph_entries.append({
            "cp": cp,
            "x": 0.0, "y": 0.0, "w": 0.0, "h": 0.0,
            "x_off": 0.0, "y_off": 0.0, "adv": float(advance)
        })
        continue

    gw = bbox[2] - bbox[0]
    gh = bbox[3] - bbox[1]

    if cur_x + gw + PADDING > ATLAS_W:
        cur_x = PADDING
        cur_y += max_row_h + PADDING
        max_row_h = 0

    if cur_y + gh + PADDING > ATLAS_H:
        print(f"Error: Atlas full at char '{ch}' (cp {cp})! cur_y={cur_y}, gh={gh}")
        sys.exit(1)

    # Draw glyph at position
    # In Pillow, text draw (x, y) draws with top-left of bbox at (x + bbox[0], y + bbox[1])
    draw_pos_x = cur_x - bbox[0]
    draw_pos_y = cur_y - bbox[1]
    draw.text((draw_pos_x, draw_pos_y), ch, fill=(255, 255, 255, 255), font=font)

    advance = font.getlength(ch)
    max_row_h = max(max_row_h, gh)

    glyph_entries.append({
        "cp": cp,
        "x": float(cur_x),
        "y": float(cur_y),
        "w": float(gw),
        "h": float(gh),
        "x_off": float(bbox[0]),
        "y_off": float(bbox[1]),
        "adv": float(advance)
    })

    cur_x += gw + PADDING

print(f"Atlas packed successfully. Occupied rows down to y={cur_y + max_row_h} / {ATLAS_H}")

# Ensure target directories exist
os.makedirs("src/game/assets", exist_ok=True)
os.makedirs("assets", exist_ok=True)

# 1. Save raw RGBA bytes
raw_bytes = atlas_img.tobytes("raw", "RGBA")
with open("src/game/assets/font_atlas.raw", "wb") as f:
    f.write(raw_bytes)
with open("assets/font_atlas.raw", "wb") as f:
    f.write(raw_bytes)
# Save preview PNG for inspection
atlas_img.save("src/game/assets/font_atlas.png")
print("Saved font_atlas.raw (512x512 RGBA) and font_atlas.png")

# 2. Sort glyphs by codepoint for binary search in Zig
glyph_entries.sort(key=lambda g: g["cp"])

# 3. Generate Zig source code
zig_code = []
zig_code.append("// Auto-generated by tools/generate_font_atlas.py - DO NOT EDIT MANUALLY")
zig_code.append("const std = @import(\"std\");\n")
zig_code.append("pub const ATLAS_W: f32 = 512.0;")
zig_code.append("pub const ATLAS_H: f32 = 512.0;")
zig_code.append(f"pub const BASE_FONT_SIZE: f32 = {float(FONT_SIZE)};\n")
zig_code.append("pub const GlyphInfo = struct {")
zig_code.append("    codepoint: u21,")
zig_code.append("    u0: f32,")
zig_code.append("    v0: f32,")
zig_code.append("    u1: f32,")
zig_code.append("    v1: f32,")
zig_code.append("    w: f32,")
zig_code.append("    h: f32,")
zig_code.append("    x_off: f32,")
zig_code.append("    y_off: f32,")
zig_code.append("    advance: f32,")
zig_code.append("};\n")

zig_code.append(f"pub const GLYPHS: [{len(glyph_entries)}]GlyphInfo = [_]GlyphInfo{{")
for g in glyph_entries:
    u0 = g["x"] / ATLAS_W
    v0 = g["y"] / ATLAS_H
    u1 = (g["x"] + g["w"]) / ATLAS_W
    v1 = (g["y"] + g["h"]) / ATLAS_H
    zig_code.append(
        f"    .{{ .codepoint = {g['cp']}, "
        f".u0 = {u0:.6f}, .v0 = {v0:.6f}, .u1 = {u1:.6f}, .v1 = {v1:.6f}, "
        f".w = {g['w']:.1f}, .h = {g['h']:.1f}, "
        f".x_off = {g['x_off']:.1f}, .y_off = {g['y_off']:.1f}, "
        f".advance = {g['adv']:.1f} }},"
    )
zig_code.append("};\n")

zig_code.append("""
pub fn findGlyph(cp: u21) ?*const GlyphInfo {
    var left: usize = 0;
    var right: usize = GLYPHS.len;
    while (left < right) {
        const mid = left + (right - left) / 2;
        if (GLYPHS[mid].codepoint == cp) {
            return &GLYPHS[mid];
        } else if (GLYPHS[mid].codepoint < cp) {
            left = mid + 1;
        } else {
            right = mid;
        }
    }
    // Fallback to '?' if not found
    if (cp != '?') return findGlyph('?');
    return null;
}

pub fn measureTextWidth(text: []const u8, font_size: f32) f32 {
    const scale = font_size / BASE_FONT_SIZE;
    var total_w: f32 = 0.0;
    var utf8 = std.unicode.Utf8View.init(text) catch return @as(f32, @floatFromInt(text.len)) * 8.0 * scale;
    var iter = utf8.iterator();
    while (iter.nextCodepoint()) |cp| {
        if (findGlyph(cp)) |glyph| {
            total_w += glyph.advance * scale;
        } else {
            total_w += 8.0 * scale;
        }
    }
    return total_w;
}
""")

with open("src/game/font_data.zig", "w", encoding="utf-8") as f:
    f.write("\n".join(zig_code))

print("Generated src/game/font_data.zig successfully!")
